#:schema node_modules/wrangler/config-schema.json
name = "cf-flathub-reverse-proxy"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
USERNAME = "none"
PASSWORD = "none"
